# Generated by Django 5.1.3 on 2024-11-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('view_all_students', 'Can view all students'), ('view_own_students', 'Can view own students')]},
        ),
    ]
