# Generated by Django 5.1.3 on 2024-11-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
