# Generated by Django 5.1.3 on 2024-11-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('course', 'Course Notification'), ('general', 'General Notification')], default='general', max_length=20),
        ),
    ]
